### ISSUE TITLE
Add change password and change username endpoints

### ISSUE THREAD

**Issue by Tomislaw** [Open-Model-Initiative/OMI-Data-Pipeline#11]
# Add change password and change username endpoints

## Description
Add two new endpoints. One for changing password and another for changing username
Changing password should remove all sessions (log out from all devices)
Add minimum requirements for password
Add for username

## Checklist
- [ ] /auth/change-password
- [ ] /auth/change-username

**Comment by AshishKmrSingh** [comment]
Hello. I visited the contribution doc. It says it is WIP for the steps to contribute. How can I contribute to these sets of 'good first issues'?

**Comment by Tomislaw** [comment]
Hey @AshishKmrSingh,

Feel free to create PR for tasks you think you are able to finish. 

If you don't have permissions for creating PR, please contact @hipsterusername on Discord.

**Comment by CheesyLaZanya** [comment]
@AshishKmrSingh 

Just to elaborate here, we've just officially switched over to public work mode for these repositories so unfortunately a few things like a full guide on how to contribute or a more thorough getting started document are not yet ready but should be something we build out more very soon.

In the meantime the most useful way to get started would likely be to follow the setup document that currently lives here: https://github.com/Open-Model-Initiative/OMI-Data-Pipeline/blob/main/docs/setup.md to try out the setup and get familiar with the project though note there may be some updates to that guide in the near future.

There will also need to be more work on breaking down and defining tasks/issues to help support community engagement as we ramp up as well which would start to let us better identify which items are best for new contributors to the project to take on vs which are more core and central to the overall progress of the project.

So we appreciate your early enthusiasm for the project here and look forward to your future contributions :)
