### ISSUE TITLE
Bootstrap Monitoring / Logging System

### ISSUE THREAD

**Issue by fearnworks** [Open-Model-Initiative/OMI-Data-Pipeline#13]
We need to create a new `odr_monitoring` module to handle logging of errors and information from our pipeline. This module will initially focus on early control flow issues but should be designed with future performance monitoring capabilities in mind.

Tasks:

1. Create a new `odr_monitoring` directory in the `modules` folder
2. Set up basic module structure:
   - `__init__.py`
   - `logger.py`
   - `config.py`
   - `handlers/`
   - `formatters/`
3. Implement a configurable logging system:
   - Use Python's built-in `logging` module
   - Create custom formatters for different log levels
   - Implement handlers for console and file output
4. Design an easy-to-use API for other modules to utilize the logging functionality
5. Implement basic error and info logging functions
6. Add configuration options for log levels, output destinations, and rotation policies
7. Write basic documentation for usage and configuration
9. Add basic tests for core logging functionality

Acceptance Criteria:

- [ ] `odr_monitoring` module is created and integrated into the project structure
- [ ] Logging system is implemented and configurable
- [ ] Other modules can easily use the logging functionality
- [ ] Basic error and info logging are functional
- [ ] Configuration options for logging are available and documented
- [ ] Placeholder for future performance monitoring is in place
- [ ] Tests are written and passing
- [ ] Documentation for usage and configuration is available

**Comment by robert-cronin** [comment]
I would like to work on this one, if no one else has started
