### ISSUE TITLE
In `reset-postgres` task, volume name to remove is incorrect

### ISSUE THREAD

**Issue by CheesyLaZanya** [Open-Model-Initiative/OMI-Data-Pipeline#17]
In the taskfile.yml for odr_database, 
https://github.com/Open-Model-Initiative/OMI-Data-Pipeline/blob/main/modules/odr_database/Taskfile.yml#L43

We see an attempt to remove a docker volumne "odr_database_postgres_data"

`docker volume rm odr_database_postgres_data`

In postgres-compose.yml we can see the volume names, under the 'omi-postgres' service.

https://github.com/Open-Model-Initiative/OMI-Data-Pipeline/blob/main/modules/odr_database/docker/postgres-compose.yml#L31

These expand to "omi-postgres_pgadmin_data" and "omi-postgres_postgres_data"

![image](https://github.com/user-attachments/assets/950a7ad7-ac26-419a-899f-a3fa3a962e67)

As such when you try to run the "reset-postgres" task, you get `Error response from daemon: get odr_database_postgres_data: no such volume`

**Comment by PrateekKumar1709** [comment]
Hi @CheesyLaZanya , I'd like to work on this issue. Please let me know if I can proceed. Thanks!

**Comment by CheesyLaZanya** [comment]
Hi @PrateekKumar1709 

Go for it, I've assigned the issue to you :+1:

**Comment by PrateekKumar1709** [comment]
@CheesyLaZanya I've taken the liberty to enhance the solution by:

- Implementing environment variables
```
vars:
  COMPOSE_FILE: ${ROOT_DIR}/modules/odr_database/docker/postgres-compose.yml
  POSTGRES_VOLUME_NAME: omi-postgres_postgres_data
```
- Using Task's {{.VAR_NAME}} syntax for expansion
```
docker compose -f {{.COMPOSE_FILE}} up
```

These changes enhance flexibility, consistency, and maintainability across environments. They also reduce the risk of volume name mismatches in the future. Please let me know your thoughts.
