### ISSUE TITLE
Add flake8 check to the Github pipeline

### ISSUE THREAD

**Issue by CheesyLaZanya** [Open-Model-Initiative/OMI-Data-Pipeline#19]
As we open up the project further, we shouldn't solely rely on checks running on contributors local machines.

Add the existing Flake8 linting as a pipeline check which needs to pass before PRs can be accepted.

**Comment by PrateekKumar1709** [comment]
Hi @CheesyLaZanya, I'd like to volunteer to work on this issue. My proposed approach is as follows:

- Add a .flake8 configuration file to the root directory to define project-specific Flake8 rules.
- Create a new GitHub Actions workflow file (e.g., flake8.yml) in the .github/workflows directory to run Flake8 checks on all pull requests.
- Update the main Taskfile.yml to include a lint task that runs Flake8 locally, allowing developers to check their code before pushing.
- Modify the CONTRIBUTING.md file to include instructions on running the Flake8 check locally and explain its importance in the PR process.
- Test the implementation thoroughly to ensure it works as expected in the GitHub pipeline.

Please let me know if I can proceed with this implementation.

**Comment by CheesyLaZanya** [comment]
Hello @PrateekKumar1709 and thank you for your interest in this issue!

To note, flake8 itself has already been added to the project for local development, so the configuration file already exists: https://github.com/Open-Model-Initiative/OMI-Data-Pipeline/blob/main/.flake8

It is also part of our pre-commit hooks so _if_ someone has setup the project properly locally it will run before each commit.

This item was intended to be sure it was checked in the pipeline just in case someone submitted a PR that looks reasonable but did not have the local setup done correctly and the pre-commit did not run, for extra safety/peace of mind.


So with that said if you are able to add the GitHub action still that would be great!

And if you want to add a task to run the local setup manually, I suggest making the task run `pre-commit run --all-files ` since that would run flake8 + our other pre-commit checks.

I will assign this issue to you now but let me know if you have any questions or concerns.

Thanks!

**Comment by PrateekKumar1709** [comment]
Hi @CheesyLaZanya, apologies for missing out on the key details and thanks for highlighting them. I will work on the Github action. Thanks

**Comment by PrateekKumar1709** [comment]
Also I was thinking of adding a Flake8 annotation step to the GitHub Actions workflow. This will enhance the code review process by automatically highlighting Flake8 issues directly in pull requests and contributors can see Flake8 issues directly in their PR, without needing to check CI logs. Here's the relevant part of the workflow:
```
- name: Annotate Flake8 issues
  uses: reviewdog/action-flake8@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    reporter: github-pr-review
```
Let me know if you'd like me to proceed with implementing this or if you have any suggestions or concerns

**Comment by CheesyLaZanya** [comment]
@PrateekKumar1709 That looks like a reasonable addition to me :+1:
