### ISSUE TITLE
Add smoke tests for services

### ISSUE THREAD

**Issue by fearnworks** [Open-Model-Initiative/OMI-Data-Pipeline#3]
Description:
We need to implement smoke tests to verify that our core services are up and running after deployment. This will help ensure the reliability of our deployments and quickly identify any issues.

Tasks:
1. Create a smoke test for the API server
   - Implement a simple health check endpoint in the API
   - Write a test that calls this endpoint and verifies the response
   - Connect to a taskfile
2. Create a smoke test for the Postgres database
   - Implement a basic database connection check
   - Write a test that attempts to connect to the database and perform a simple query
   - Connect to a taskfile

There should be a command that runs both integration smoke tests 

Things to consider in the future: 
Integrate these tests into our deployment pipeline
   - Add a step in the deployment process to run these smoke tests
   - Configure the pipeline to fail if the smoke tests don't pass

**Comment by PrateekKumar1709** [comment]
Hi @fearnworks, I would like to work on this issue.
Here’s how I plan to address the issue:

**API Health Check:**

- Create a new endpoint in modules/odr_api/odr_api/api/endpoints/health.py to verify the API is running.
- Write a test in modules/odr_api/tests/test_health.py using pytest to call this endpoint and check for a successful response.

**Postgres Database Connection Test:**

- Develop a test script in modules/odr_database/tests/test_db_connection.py to confirm a successful connection to the Postgres database using the Docker Compose setup.
- Ensure the test performs a simple query to validate connectivity.

**Taskfile Integration:**

- Update the Taskfile.yml in both odr_api and odr_database to include tasks for running these smoke tests.
- Add a combined task in the root Taskfile.yml to execute both tests with a single command: task smoke_tests.

Please let me know if I can proceed with this implementation.

**Comment by fearnworks** [comment]
@PrateekKumar1709  : This sounds like a good approach. Feel free to reach out if you have any issues!

**Comment by aryam-juneja** [comment]
@PrateekKumar1709 Hi, I am new to Open Source, and would like to get started. Would you mind if we could work on this issue together?

**Comment by PrateekKumar1709** [comment]
> * Add a combined task in the root Taskfile.yml to execute both tests with a single command: task smoke_tests.

@aryam-juneja Unfortunately I have finished most of the work on this. But happy to tag team on another issue if you want. Thanks.

**Comment by aryam-juneja** [comment]
> > * Add a combined task in the root Taskfile.yml to execute both tests with a single command: task smoke_tests.
> 
> @aryam-juneja Unfortunately I have finished most of the work on this. But happy to tag team on another issue if you want. Thanks.

Okay, Lets connect in future for tag team on other issues.
