### ISSUE TITLE
Add trust mode for pgAdmin and auto-authente the db in compose file

### ISSUE THREAD

**Issue by robert-cronin** [Open-Model-Initiative/OMI-Data-Pipeline#36]
It's possible to have the local db compose stack auto authenticated. If it's only for localhost, it might be more convenient to add a pass file and set the postgres auth method to trust. This way, you won't need to enter a password in the browser, and the database will already be authenticated when you load in.

For reference, you can check out this recent project I worked on that has a local dev database + pgadmin: 

https://github.com/robert-cronin/jueju/tree/main/backend/local-db

I can add it in if it's a good idea!

**Comment by fearnworks** [comment]
Yes please!
