### ISSUE TITLE
Verify Data Model

### ISSUE THREAD

**Issue by fearnworks** [Open-Model-Initiative/OMI-Data-Pipeline#7]
# Data Model Implementation and Verification

Doc link : https://github.com/Open-Model-Initiative/OMI-Data-Pipeline/blob/main/modules/odr_datamodel/data_model_overview.md

## Description

Implement and verify the data model for the OMI Data Pipeline. This task includes setting up comprehensive tests for CRUD operations on all entities and ensuring alignment with the documented specifications from the working group meeting notes.

### Data Model Implementation & Verification
- [x] User
- [ ] Team
- [ ] TeamUser
- [x] Content
- [ ] ContentAuthor
- [ ] ContentEmbedding
- [ ] EmbeddingEngine
- [ ] ContentEvents
- [ ] ContentReport
- [ ] ContentSet
- [x] Annotation
- [ ] AnnotationEmbedding
- [ ] AnnotationRating
- [ ] AnnotationReport
- [ ] AnnotationSource

### Test Setup
- [ ] Implement create tests for all entities
- [ ] Implement read tests for all entities
- [ ] Implement update tests for all entities
- [ ] Implement delete tests for all entities

### Documentation Update
- [ ] Update data_model_overview.md with any changes or clarifications
- [ ] Ensure all fields are properly documented, including those added during sandbox process
- [ ] Document any deferred fields or features

## Additional Notes
- Refer to the working group meeting notes for the most up-to-date specifications.
- Ensure that the relationship between Annotations and Content is properly implemented and tested.

**Comment by fearnworks** [comment]
Merge #14 was only a partial for auth

**Comment by robert-cronin** [comment]
I would love to work on this one if no one else has started!

**Comment by fearnworks** [comment]
Yea, most of the notes are in the discord. Would definitely appreciate the help on this one! Currently we just have the core models defined out. Kent mentioned reaching out to get you looped in so be on the lookout for comms from somewhere.

**Comment by robert-cronin** [comment]
> Yea, most of the notes are in the discord. Would definitely appreciate the help on this one! Currently we just have the core models defined out. Kent mentioned reaching out to get you looped in so be on the lookout for comms from somewhere. 

Gotcha, thanks @fearnworks. I'll be on the lookout! FYI I'm Rob (dilbert_1) on discord! :)
